log_dir: logs
config_dir: ""
processes:
    - name: process1
      command: /C
      args:
        - Hello,
        - World!
      env: []
      work_dir: .
      max_instances: 1
      auto_start: true
    - name: process2
      command: python
      args:
        - script.py
      env: []
      work_dir: .
      max_instances: 1
      auto_start: true
